// Generated by CoffeeScript 1.3.3
var Mailer, Mailman;

Mailer = require('nodemailer');

Mailman = (function() {

  function Mailman() {}

  Mailman.connect = function(params) {
    var transport;
    transport = params.service.toLowerCase() === 'ses' ? 'SES' : 'SMTP';
    params.auth = {
      user: params.user,
      pass: params.password
    };
    params.secureConnection = !!params.ssl;
    return this.transport = Mailer.createTransport(transport, params);
  };

  Mailman.setup = function(model) {
    model.prototype.transport = this.transport;
    return model;
  };

  return Mailman;

})();

Mailman.Model = (function() {

  function Model() {
    this.attachments = [];
    this.generateTextFromHTML = true;
  }

  Model.prototype.deliver = function(callback) {
    var key, keys, params, _i, _len;
    keys = ['from', 'to', 'cc', 'bcc', 'replyTo', 'subject', 'text', 'html', 'headers', 'attachments', 'encoding'];
    params = {};
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      key = keys[_i];
      if (this[key] && this[key].length > 0) {
        params[key] = this[key];
      }
    }
    return this.transport.sendMail(params, callback);
  };

  Model.prototype.send = function() {
    return this.deliver.apply(this, arguments);
  };

  return Model;

})();

module.exports = Mailman;
